# Generated by Django 4.0.2 on 2022-02-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='balanceinfo',
            name='bal',
            field=models.IntegerField(default=0),
        ),
    ]
