# Generated by Django 4.0.2 on 2022-02-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_balanceinfo_bal'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bal', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='BalanceInfo',
        ),
        migrations.DeleteModel(
            name='UserName',
        ),
    ]
